#!/bin/bash

# usage: ./do_gen_fft_large INSTANCE_NAME

# generates a large fft and axi wrapper in a single file
# outputs to ../generated/INSTANCE_NAME_large_axi.vhd

NAME="$1"
OUTFILE="../generated/${NAME}_large_axi.vhd"

./gen_fft.py fft "$NAME" - >"$OUTFILE"
./gen_fft.py reorderer "$NAME" - >>"$OUTFILE"
./gen_fft.py large "$NAME" - >>"$OUTFILE"

