#!/bin/bash

NAME="$1"
OUTDIR="../generated/$NAME"

mkdir -p "$OUTDIR"
./gen_fft.py fft "$NAME" "$OUTDIR"
./gen_fft.py reorderer "$NAME" "$OUTDIR"
./gen_fft.py wrapper "$NAME" "$OUTDIR"
./gen_fft.py large "$NAME" "$OUTDIR"

